import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { dbConnect } from "@/services/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  dbConnect()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar sidebar={false} />
        <main>
        {children}
        </main>
        </body>
    </html>
  );
}
